add_newline = true
command_timeout = 1000

format = """
[┌─](bold #b16286)$directory$git_branch$git_status$nodejs$python$rust$golang$typst
[└─](bold #b16286)$character"""

[character]
success_symbol = "[❯](#d79921)"
error_symbol = "[❯](#cc241d)"
vimcmd_symbol = "[❮](#98971a)"

[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style) "
style = "bold #458588"

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = " "
style = "bold #b16286"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold #d79921"
conflicted = "🏳"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = "$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[nodejs]
format = "via [$symbol($version )]($style)"
symbol = " "
style = "bold #98971a"

[python]
format = "via [$symbol$pyenv_prefix($version )]($style)"
symbol = " "
style = "bold #d79921"

[rust]
format = "via [$symbol($version )]($style)"
symbol = " "
style = "bold #cc241d"

[golang]
format = "via [$symbol($version )]($style)"
symbol = " "
style = "bold #689d6a"

[typst]
format = "via [$symbol($version )]($style)"
symbol = "t "
style = "bold #458588"

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
style = "bold #d79921"

[package]
disabled = true
